### PR TITLE
Vector2Parameter using PlanarPad

### PR DESCRIPTION
**Pull request by reinvdwoerd**

### CODE REVIEW

**Comment by ricardomatias** [comment]
Regarding the `Vector2Parameter` annotation, if we keep the naming Vector2 then we should accept Vector2s. Or I'd rename it to XYParameter/PlanarParameter to tie it with the gui's part.

**Comment by reinvdwoerd** [comment]
Hmm, the annotation can't take a Vector2, it has to be primitives...


Screenshot 2020-03-18 at 11 03 45

**Comment by ricardomatias** [comment]
Yes, the values have to be defined at compile time (I just bumped into that issue). Maybe the naming will change depending on the other PR's discussion.

The annotation itself needs more parameters. It needs to have the precision as well as the increment for the keyboard interaction.

**Comment by reinvdwoerd** [comment]
Ah, yeah I think it's better to separate the keyboard increment from the precision

**Comment by edwinRNDR** [comment]
I would not name this `Vector2Parameter` 

Not all `Vector2` properties should be treated in the same way. For _some_ cases one will want to use `XYPad`, here one could use `XYParameter`. For other cases one may want to use two sliders instead of a pad based control.  In general there is not enough context to infer which control to use; in the end it is a choice for whoever annotates their properties.

**Comment by reinvdwoerd** [comment]
Ok, then I'll rename it...

**Comment by edwinRNDR** [comment]
Squashed and merged in https://github.com/openrndr/orx/commit/9fac66fff0e1859db0f4d88f4dabd444c686b75c

I have made some small changes to the annotation: 
 * removed keyboardIncrement (as I did from the control)
 * re-ordered minX, minY, maxX, maxY to minX, maxX, minY, maxY
 * add invertY

**Pull request closed without merging**
