### PR TITLE
Merge from 0.3 branch

### PR DESCRIPTION
**Pull request by jbellis**

### CODE REVIEW

**Comment by edwinRNDR** [comment]
I don't think aa2c60c should be pulled into master? I'll try to merge 7142a95 into master

**Comment by edwinRNDR** [comment]
Fixed in 6e00ca2ea1da11f0c4b4dce629c1fa9033ca6fbe

**Comment by jbellis** [comment]
I may have missed something but what I did was do a full merge from 0.3 branch and then edited out the changes from that commit.  That way "git merge 0.3" will "just work" next time

**Comment by jbellis** [comment]
Do you prefer a "commit to master and cherry pick to older branches" workflow?

**Comment by edwinRNDR** [comment]
Yes please!

**Pull request closed without merging**
