### PR TITLE
[orx-noise]: Make random int's range inclusive

### PR DESCRIPTION
**Pull request by ricardomatias**

### CODE REVIEW

**Comment by hamoid** [comment]
That's a big change. Is it good to change this now? Some of my program will break, when I use the random int value as the index for a list, expecting the max value to be size - 1...

**Comment by ricardomatias** [comment]
It is a breaking change, but we should figure out if this default makes more sense or not. I'll also have to fix some programs, but today I was faced with thinking it was inclusive, since other tools that I use have this as default. Any thoughts on why it should or shouldn't be?

**Comment by hamoid** [comment]
Isn't it odd if it's inclusive for Int but non inclusive for Double?

**Comment by morisil** [comment]
Kotlin stdlib is solving this ambiguity by having extra `Random.nextInt(IntRage)` where conveniently range can be define as inclusive or not, so it can be called like this:

```kotlin
  Random.nextInt(0..10)
  Random.nextInt(0 until 10)
```

I really like this explicit semantics of Kotlin, where ranges are part of the language idioms. So I would rather suggest to overload `int` function with `int(IntRage)` rather than changing the default which is following what's in kotlin stdlib.

**Comment by morisil** [comment]
When I think about this, which one would you rather use?

```kotlin
Random.int0(100) // max 99
Random.int(0..100) // max 100
```

**Comment by hamoid** [comment]
I prefer the 0 not being part of the method name. What about performance? Does it make a difference?

**Comment by ricardomatias** [comment]
I don't think we have to choose, we can add another function signature for ranges which is a good addition. Both `int0` and `double0` have their use cases. We definitely need documentation though.  

> Isn't it odd if it's inclusive for Int but non inclusive for Double?

I want to create a distribution and see how it looks like for the range of 0 and 2 to see if it's uniform throughout.

**Comment by edwinRNDR** [comment]
Exclusive ranges look to be the convention in Java's and Kotlin's standard libraries, I see no good arguments for breaking with those.

**Comment by ricardomatias** [comment]
Closing this in favor of keeping it as it is.

**Pull request closed without merging**
